### ISSUE TITLE
Application crashes on mobile

### ISSUE THREAD

**Issue by anilsathyan7** [wonderit/indoor-segmentation-android#4]
The application was build successfully using android studio; but it crashes on the device

Here is the error output:-
I/tensorflow: TensorFlowDeeplabV3PlusDetector: output names SemanticPredictions 
E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[ImageTensor], outputs:[SemanticPredictions]
E/AndroidRuntime: FATAL EXCEPTION: inference
                  Process: org.tensorflow.demo, PID: 14412
                  java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Slice' with these attrs.  Registered devices: [CPU], Registered kernels:
                    device='CPU'; T in [DT_BOOL]
                    device='CPU'; T in [DT_FLOAT]
                    device='CPU'; T in [DT_INT32]

**Comment by wonderit** [comment]
Sorry for late reply @anilsathyan7  

I believe the libtensorflow_inference.so that I built has no support for INT64 currently on your device, from the logs, we can see that only INT32, FLOAT, BOOL is registered, no INT64. 

I solved this problem by building libtensorflow_inference.so file manually for armeabi-v7a cpu. (not by downloading from the nightly build)

I modified the register_types.h to enable INT64 on the device.
I edited two lines

1. [line1](https://github.com/tensorflow/tensorflow/blob/70ef6c3e50037b39f2c033317721eef1cbde2004/tensorflow/core/framework/register_types.h#L127) ->
`#define TF_CALL_uint8(m) m(::tensorflow::uint8)`
2. [line2](https://github.com/tensorflow/tensorflow/blob/70ef6c3e50037b39f2c033317721eef1cbde2004/tensorflow/core/framework/register_types.h#L135) ->
`#define TF_CALL_int64(m) m(::tensorflow::int64)`

I think you should modify the register_types.h code like the above and build the libtensorflow_inference.so that matches your device. And then put the library to jniLibs/arm64-v8a
(if your device is arm64-v8a)
`
bazel clean && \
    bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so \
    --crosstool_top=//external:android/crosstool \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --cpu=arm64-v8a
`

**Comment by anilsathyan7** [comment]
We are facing another build issue when we ran this command

$ bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=arm64-v8a

ERROR: Failed to load Skylark extension '//tensorflow:version_check.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository '' was defined later in your WORKSPACE file?
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.049s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

How can we resolve this issue?

**Comment by wonderit** [comment]
I uploaded the libtensorflow_inference.so for arm64-v8a.

please try with this.

**Comment by anilsathyan7** [comment]
Thanks, now the application is working fine without any issues.

The speed and accuracy seems to be low though.How can we improve them?
How do you convert a frozen_graph.pb to quantized_graph.pb (not tflite)?

Any help would be greatly appreciated...

**Comment by wonderit** [comment]
I faced the same problem. I reduced the crop size to speed up. (e.g. 513x513 to 129x129)...
The accuracy and speed has trade-off.. so smaller than 129x129 may be inaccurate.

You can convert a frozen_graph.pb to quantized_graph.pb with the link below.
[link](https://github.com/wonderit/indoor-segmentation-android/blob/ed1ee12f2a80931a632af9fb303882719d04de16/assets/bazel_scripts.sh#L47)

**Comment by tbbjymm21** [comment]
> We are facing another build issue when we ran this command
> $ bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=arm64-v8a
> ERROR: Failed to load Skylark extension '//tensorflow:version_check.bzl'.
> It usually happens when the repository is not defined prior to being used.
> Maybe repository '' was defined later in your WORKSPACE file?
> ERROR: cycles detected during target parsing
> INFO: Elapsed time: 0.049s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> How can we resolve this issue?

How did you solve this problem？Could you tell me？Thank you very much!

**Comment by wonderit** [comment]
Please check if you have another workspace under tensorflow subdirectories. You might accidentally built from this sub dir before. In my case, the problem went away once I deleted the subdir.
